live_config_reload: true

# Window configs
window:
  opacity: 0.9
  padding:
    x: 10
    y: 20
  dynamic_padding: true
  decorations: buttonless

# Font styles
font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular
  size: 14.0

import:
  - ~/.config/alacritty/thm/tokyo-night.yaml
